namespace MdrrmoCameraAgent.Mtx;

public static class MediaMtxConfigWriter
{
    public static string Render(IEnumerable<CameraEntry> cameras)
    {
        foreach (var c in cameras)
        {
            if (c.StreamPath.Contains('\n') || c.StreamPath.Contains('\r'))
                throw new ArgumentException($"CameraEntry.StreamPath must not contain newline characters: '{c.Id}'");
            if (c.RtspUrl.Contains('\n') || c.RtspUrl.Contains('\r'))
                throw new ArgumentException($"CameraEntry.RtspUrl must not contain newline characters: '{c.Id}'");
            if (c.WhipUrl is not null && (c.WhipUrl.Contains('\n') || c.WhipUrl.Contains('\r')))
                throw new ArgumentException($"CameraEntry.WhipUrl must not contain newline characters: '{c.Id}'");
        }

        var publishable = cameras.Where(c => c.WhipUrl is not null).ToList();

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Auto-generated by MdrrmoCameraAgent. Do not edit by hand.");
        sb.AppendLine("logLevel: info");
        sb.AppendLine("logDestinations: [stdout]");
        sb.AppendLine("api: yes");
        sb.AppendLine("apiAddress: 127.0.0.1:9997");

        if (publishable.Count == 0)
        {
            // Registration-only mode: hub URL is null OR no cameras enrolled yet.
            // mediamtx.exe must still parse the yml without errors.
            sb.AppendLine("paths: {}");
            return sb.ToString();
        }

        sb.AppendLine("paths:");
        foreach (var c in publishable)
        {
            sb.AppendLine($"  {c.StreamPath}:");
            sb.AppendLine($"    source: {c.RtspUrl}");
            sb.AppendLine($"    sourceOnDemand: no");
            // ffmpeg -i rtsp://127.0.0.1:8554/<MTX_PATH> -c copy -f whip <WHIP_URL>
            //   $MTX_PATH is substituted by MediaMTX at exec time; the WHIP URL is
            //   render-time so PublishTokenRefresher can hot-swap it via /v3/config/paths/replace.
            sb.AppendLine($"    runOnReady: ffmpeg -hide_banner -loglevel warning -i rtsp://127.0.0.1:8554/$MTX_PATH -c copy -f whip \"{c.WhipUrl}\"");
            sb.AppendLine($"    runOnReadyRestart: yes");
        }
        return sb.ToString();
    }

    public static void WriteToFile(string path, IEnumerable<CameraEntry> cameras)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Render(cameras));
    }
}
