namespace MdrrmoCameraAgent.Mtx;

public static class MediaMtxConfigWriter
{
    public static string Render(IEnumerable<CameraEntry> cameras)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Auto-generated by MdrrmoCameraAgent. Do not edit by hand.");
        sb.AppendLine("logLevel: info");
        sb.AppendLine("logDestinations: [stdout]");
        sb.AppendLine("api: yes");
        sb.AppendLine("apiAddress: 127.0.0.1:9997");
        sb.AppendLine("paths:");
        foreach (var c in cameras)
        {
            sb.AppendLine($"  {c.StreamPath}:");
            sb.AppendLine($"    source: {c.RtspUrl}");
            sb.AppendLine($"    sourceOnDemand: no");
            // ffmpeg -i rtsp://127.0.0.1:8554/<MTX_PATH> -c copy -f whip <WHIP_URL>
            //   $MTX_PATH is substituted by MediaMTX at exec time; the WHIP URL is
            //   render-time so PublishTokenRefresher can hot-swap it via /v3/config/paths/replace.
            sb.AppendLine($"    runOnReady: ffmpeg -hide_banner -loglevel warning -i rtsp://127.0.0.1:8554/$MTX_PATH -c copy -f whip \"{c.WhipUrl}\"");
            sb.AppendLine($"    runOnReadyRestart: yes");
        }
        return sb.ToString();
    }

    public static void WriteToFile(string path, IEnumerable<CameraEntry> cameras)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Render(cameras));
    }
}
